### PR TITLE
Slim down the collectd image

### PR DESCRIPTION
**Pull request by adamdecaf**
I don't think we're versioning this docker image, so if we build and push this to the registry it might get auto deployed out. 

Issue: https://github.com/Banno/infrastructure/issues/383

### CODE REVIEW

**Comment by adamdecaf** [comment]
This slims down to 

```
~/src/banno/containers/docker-collectd $ docker images | grep collectd
banno/docker-collectd                                            latest              8392b455adee        2 minutes ago        175.4 MB
```

From 

```
registry.banno-internal.com/collectd-host-sidecar      latest              de3f726cf2d0        4 months ago        1.12 GB
```

**Comment by sherzberg** [comment]
👍 damn

**Comment by adamdecaf** [comment]
It turns out we need to compile collectd. I tried autoremoving some packages and a couple things broke.

```
~/src/banno/containers/docker-collectd $ docker images | grep 374b3fcd8a56
banno/docker-collectd                                            latest              374b3fcd8a56        59 seconds ago      351.4 MB
```

**Comment by adamdecaf** [comment]
We can likely remove `build-essential` after compile as long as the underlying runtimes are around in this debian image.

**Comment by DustinChaloupka** [comment]
👍

**Comment by arreyder** [comment]
+1

In the future maybe we should just have a collectd build in jenkins making an apt package out of this, so no need to pull out build related things.

**Pull request merged**
